# Generated by Django 3.1.5 on 2021-05-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.TextField(max_length=500)),
                ('product_brand', models.TextField(max_length=500)),
                ('product_type', models.TextField(max_length=500)),
                ('product_description', models.TextField(max_length=500)),
                ('product_price', models.TextField(default=0, max_length=100)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField(max_length=500)),
                ('phone_no', models.IntegerField()),
                ('total_price', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='core.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('total_price', models.IntegerField(default=0)),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('items', models.ManyToManyField(to='core.Item')),
            ],
        ),
    ]
